@baseUrl = http://localhost:7600
@urlPath = api/v1

###
POST  {{baseUrl}}/{{urlPath}}/auth/register
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "username": "isaacoduh",
    "email": "ufuomaoduh@gmail.com",
    "password": "password"
}

###
POST {{baseUrl}}/{{urlPath}}/auth/login
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "email": "ufuomaoduh@gmail.com",
    "password": "password"
}

###
GET {{baseUrl}}/{{urlPath}}/auth/me
Content-Type: application/json
Accept: application/json
withCredentials: true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMmRiZDdmZS0wZDkwLTRlODEtYThiMC1iMWM5ZGFkYmZlZmEiLCJpYXQiOjE3MjA5MzI1NjMsImV4cCI6MTcyMTAxODk2M30.eSXR_0IKB6Dpv25VfT8VXGAZKp6FlHITUoSPyecWeoQ
